/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as DrugsRouteImport } from './routes/drugs'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as PeriodRouteImport } from './routes/period'
import { Route as SosRouteImport } from './routes/sos'
import { Route as WellnessRouteImport } from './routes/wellness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugsRoute = DrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodRoute = PeriodRouteImport.update({
  id: '/period',
  path: '/period',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/baby': typeof BabyRoute
  '/drugs': typeof DrugsRoute
  '/family': typeof FamilyRoute
  '/first-aid': typeof FirstAidRoute
  '/health': typeof HealthRoute
  '/hospitals': typeof HospitalsRoute
  '/insurance': typeof InsuranceRoute
  '/period': typeof PeriodRoute
  '/sos': typeof SosRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/baby': typeof BabyRoute
  '/drugs': typeof DrugsRoute
  '/family': typeof FamilyRoute
  '/first-aid': typeof FirstAidRoute
  '/health': typeof HealthRoute
  '/hospitals': typeof HospitalsRoute
  '/insurance': typeof InsuranceRoute
  '/period': typeof PeriodRoute
  '/sos': typeof SosRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/baby': typeof BabyRoute
  '/drugs': typeof DrugsRoute
  '/family': typeof FamilyRoute
  '/first-aid': typeof FirstAidRoute
  '/health': typeof HealthRoute
  '/hospitals': typeof HospitalsRoute
  '/insurance': typeof InsuranceRoute
  '/period': typeof PeriodRoute
  '/sos': typeof SosRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/baby'
    | '/drugs'
    | '/family'
    | '/first-aid'
    | '/health'
    | '/hospitals'
    | '/insurance'
    | '/period'
    | '/sos'
    | '/wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/baby'
    | '/drugs'
    | '/family'
    | '/first-aid'
    | '/health'
    | '/hospitals'
    | '/insurance'
    | '/period'
    | '/sos'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/baby'
    | '/drugs'
    | '/family'
    | '/first-aid'
    | '/health'
    | '/hospitals'
    | '/insurance'
    | '/period'
    | '/sos'
    | '/wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  BabyRoute: typeof BabyRoute
  DrugsRoute: typeof DrugsRoute
  FamilyRoute: typeof FamilyRoute
  FirstAidRoute: typeof FirstAidRoute
  HealthRoute: typeof HealthRoute
  HospitalsRoute: typeof HospitalsRoute
  InsuranceRoute: typeof InsuranceRoute
  PeriodRoute: typeof PeriodRoute
  SosRoute: typeof SosRoute
  WellnessRoute: typeof WellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugs': {
      id: '/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/period': {
      id: '/period'
      path: '/period'
      fullPath: '/period'
      preLoaderRoute: typeof PeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  BabyRoute: BabyRoute,
  DrugsRoute: DrugsRoute,
  FamilyRoute: FamilyRoute,
  FirstAidRoute: FirstAidRoute,
  HealthRoute: HealthRoute,
  HospitalsRoute: HospitalsRoute,
  InsuranceRoute: InsuranceRoute,
  PeriodRoute: PeriodRoute,
  SosRoute: SosRoute,
  WellnessRoute: WellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
