/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as HealthRouteImport } from './routes/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/family': typeof FamilyRoute
  '/health': typeof HealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/family': typeof FamilyRoute
  '/health': typeof HealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/family': typeof FamilyRoute
  '/health': typeof HealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baby' | '/family' | '/health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/baby' | '/family' | '/health'
  id: '__root__' | '/' | '/baby' | '/family' | '/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BabyRoute: typeof BabyRoute
  FamilyRoute: typeof FamilyRoute
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BabyRoute: BabyRoute,
  FamilyRoute: FamilyRoute,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
